[shared-settings]
enable=true
topas4_port=8000
serial = "16426"

[crystal]
motor_index=1
port=39101

[amplifier]
motor_index=2
port=39102

[grating]
motor_index=3
port=39103

[ndfg_crystal]
motor_index=4
port=39104

[ndfg_mirror]
motor_index=5
port=39105

[ndfg_delay]
motor_index=6
port=39106
